# Identificadores del proyecto

sonar.projectKey=proyecto-devsecops

sonar.projectName=Sistema Seguro DevSecOps



# ¿Qué carpetas vamos a escanear? (Nuestros 3 castillos)

sonar.sources=sistema-a/src, sistema-b/src, frontend/src



# Dirección de nuestro servidor SonarQube

sonar.host.url=http://localhost:9000



# Credenciales de acceso

sonar.login=admin

sonar.password=Chispo11